### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ParkDongin** [ChangeWindows/Viv#30]
**Is your feature request related to a problem? Please describe.**
Please support Korean.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Studio384** [comment]
ChangeWindows is for the most part written content. Asking us to support Korean is like asking any other newssite to support another langauge. While I'd love for ChangeWindows to be available in more languages, it is unrealistic for me to do that.
