### ISSUE TITLE
Version 1909 not show Broad channel information

### ISSUE THREAD

**Issue by ghost** [ChangeWindows/Viv#85]
In the part that shows the versions (TAB Rings -> PC), on the 1909 Version i not see the Broad channel information
![image](https://user-images.githubusercontent.com/68008113/97573843-a23ed300-19ea-11eb-95bf-0ae3eded18fe.png)
But the broad version of 1909 exist
![image](https://user-images.githubusercontent.com/68008113/97573871-ad91fe80-19ea-11eb-998e-ed91e31ac54e.png)

I expect to see the Broad channel information as a Version 1903
![image](https://user-images.githubusercontent.com/68008113/97573917-c00c3800-19ea-11eb-9629-a81fb9e4794f.png)

App version 5.3.2

**Comment by Studio384** [comment]
This is not a bug. Merily an oversight in our data. Anyways, the Broad ring has been removed from version 1903.

**Comment by ghost** [comment]
OK thanks. Where check the active rings?

**Comment by Studio384** [comment]
Not sure what you're asking. Any of the active rings can be seen from the page you included screenshot off in this issue.

**Comment by ghost** [comment]
Sorry, you're right.
I wanted to understand which branch to install in my company device because I would always refer to the old CBB branch (Current Branch for Business), and now it seems to me that they are all Semi Annual Targeted, or the old CB. Know you the answer?
