### ISSUE TITLE
Sorting of build feed

### ISSUE THREAD

**Issue by htcfreek** [ChangeWindows/Viv#93]
**Is your feature request related to a problem?S Please describe.**
When I open build feed I have have to scroll at the end of the list to see the newest builds. For me this makes no sense because I wan't to see the newst informations.

**Describe the solution you'd like**
1. Please chang the default sorting from "old -> new" to "new -> old".
2. Add an option to change the order for users who don't like the new order.

**Describe alternatives you've considered**

**Additional context**

**Comment by Studio384** [comment]
Not sure what you mean? The Buildfeed Archive order is from new to old.

**Comment by htcfreek** [comment]
Sorry. This was my mistake. There is no sorting bug.

I expect to see some builds higher as 10.0.18318.0 listed. But they aren't listed.

**Comment by Studio384** [comment]
The Buildfeed page is an archive of the data previously hosted on Buildfeed, we have no intend on extending the data, it is purely an archive.
